language: cpp
compiler:
  - gcc
  - clang
general:
  branches:
    only:
      - master
      - Ilya

before_script:
  - mkdir ../build
  - cd ../build

script:
  - cmake ..
  - make -j
  - cd ./Tests/
  - ./Test --gtest_list_tests

notifications:
  email: true