language: C++

general:
  branches:
    only:
      - travis

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
      - python-opencv

before_install:
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF build ..
  - make -j
  - cd ..
  - cd ..
  - git clone https://github.com/google/googletest
  -  cd googletest
  - mkdir build
  - cd build
  -  cmake ..
  -  make
  -  make install
  - cd ..
  - cd ..


before_script:
  - mkdir build
  - cd build

script:
  - cmake build -DOpenCV_DIR=../opencv/build DGtest_DIR=../googletest/build ..
  - make -j
  - cd Tests/
  - ./Test

notifications:
  email: true

