language: C++

general:
  branches:
    only:
      - travis

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
      - python-opencv

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew tap ros/deps; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gtest; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; git clone https://github.com/opencv/opencv.git
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; cd opencv
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; mkdir build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; cd build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; cmake build ..
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; make -j
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; cd ..
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; cd ..


before_script:
  - mkdir build
  - cd build

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; cmake build -DOpenCV_DIR=../opencv/build ..
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; cmake build ..
  - make -j
  - cd Tests/
  - ./Test

notifications:
  email: true

