language: C++

general:
  branches:
    only:
      - travis

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev

before_install:
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF build ..
  - make -j2
  - pwd
  - cd ..
  - pwd
  - cd ..



before_script:
  - mkdir build
  - cd build

script:
  - pwd
  - cmake build -DOpenCV_DIR=./opencv/build ..
  - make -j2
  - cd Tests/
  - ./Test

notifications:
  email: true

