language: C++

general:
  branches:
    only:
      - travis

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
      - python-opencv

before_install:
  - - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi
    - - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gtest; fi
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake build ..
  - make -j
  - cd ..
  - cd ..


before_script:
  - mkdir build
  - cd build

script:
  - cmake build -DOpenCV_DIR=../opencv/build ..
  - make -j
  - cd Tests/
  - ./Test

notifications:
  email: true

