language: C++

general:
  branches:
    only:
      - travis

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
      - python3-opencv

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi



before_script:
#  - git clone https://github.com/microsoft/vcpkg.git
#  - cd vcpkg
#  - ./bootstrap-vcpkg.sh
#  - ./vcpkg install boost
#  - ./vcpkg install opencv
#  - cd ..
  - mkdir build
  - cd build

script:
  - cmake build  ..
  - make -j
  - cd Tests/
  - ./Test

notifications:
  email: true

