language: C++

general:
  branches:
    only:
      - travis

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
      - python-opencv

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap ros/deps; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gtest; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone https://github.com/opencv/opencv.git; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd opencv; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir build; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd build; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake build .. ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make -j ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd .. ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd .. ; fi


before_script:
  - mkdir build
  - cd build

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake build -DOpenCV_DIR=../opencv/build .. ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake build .. ; fi
  - make -j
  - cd Tests/
  - ./Test

notifications:
  email: true

