language: C++

general:
  branches:
    only:
      - travis

os:
#  - osx
#  - linux
  - windows

jobs:
  allow_failures:
    - os: windows

compiler:
  - gcc
#  - clang

addons:
  apt:
    packages:
      - libboost-all-dev

before_install:
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF build ..
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make -j2; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then msbuild.exe OpenCV.sln /property:VCTargetsPath="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v110"; fi
  - pwd
  - cd ..
  - pwd
  - cd ..



before_script:
  - mkdir build
  - cd build

script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then pwd; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake build -DOpenCV_DIR=./opencv/build ..; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make -j; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cd Tests/; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then ./Test; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pwd; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake build -DOpenCV_DIR=./opencv/build ..; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dotnet build NeuralNetworks.sln; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cd Tests/; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./Test; fi
#  - pwd
#  - cmake build -DOpenCV_DIR=./opencv/build ..
#  - make -j2
#  - cd Tests/
#  - ./Test

notifications:
  email: true

