os: osx
language: C++
compiler:
  - clang

general:
  branches:
    only:
      - master

addons:
  homebrew:
    packages:
      - opencv3
      - boost

before_script:
  - mkdir build
  - cd build

script:
  - cmake build ..
  - make -j
  - cd Tests/
  - ./Test

notifications:
  email: true

