language: cpp
compiler:
  - gcc-9
  - clang
  -

general:
  branches:
    only:
      - master
      - Ilya

before_script:
  - mkdir build
  - cd build

script:
  - cmake build ..
  - make -j
  - cd ./Tests/
  - ./Test --gtest_list_tests

notifications:
  email: true