os: osx
language: C++
compiler:
  - clang

general:
  branches:
    only:
      - master

before_script:
  - git clone https://github.com/microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg integrate install
  - ./vcpkg install boost
  - ./vcpkg install opencv
  - cd ..
  - mkdir build
  - cd build

script:
  - cmake build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/vcscripts\buildsystems\vcpkg.cmake ..
  - make -j
  - cd Tests/
  - ./Test

notifications:
  email: true

